### ISSUE TITLE
The S-Curve mode (读出流程的分析与优化)

### ISSUE THREAD

**Issue by habrade** [habrade/JadePix3_Software#1]
> Safe_style = True
> 指定读出数据个数
> 查询FPGA_FIFO的数据个数
> 从FPGA_FIFO中读出部分或者全部数据（块读出）
> 重复上述2/3步骤直到满足1的要求
> 如果超时还没有满足1，则异常退出
> 
> Safe_style = False
> 指定读出数据个数
> 从FPGA_FIFO中读出要求的数据量
> FPGA_FIFO空时自动填充0xFFFFFFFF
> 满足1时文件存盘
> 
> Safe_style = True适用于Global Shutter模式
> FPGA_FIFO足够大，能够存储一帧数据
> 可在jadepix_dev.start_gs( )里面增加曝光时间结束的判断，然后再启动读数据
> 可增加读数据超时的设定，超时后将已有数据写入文件提示数据量缺多少
> 
> Safe_style = False适用于Rolling Shutter模式
> 可结合DDR内存，有足够多的数据才发起读出
> 避免有大量的无效填充0xFFFFFFFF
> 可在RS调试阶段再考虑

> 利用修改后的Safe_style = True模式，完成各Sector的S-Curve扫描
> 设想中的操作流程如下：
> 设定PULSE_HI和PULSE_LO
> 启动Global Shutter
> 读出一帧数据并存为文件data_pulse_low_test_num
> 重复2/3直到test_num满足设定值（例如50次）
> 增加PULSE_LO by step size
> 重复2/3/4直到PULSE_LO满足设定值
> 
> 目前需要修改的软件：
> Page 2中提到的增加曝光时间结束判断，以及增加预设超时退出的步骤
> run.py里面实现上述循环和判断步骤（测试人员应该逐步学会修改run.py来实现自己的想法）

**Comment by habrade** [comment]
- [ ] Page 2中提到的增加曝光时间结束判断，以及增加预设超时退出的步骤
   1. lib.jadepix_dev.start_gs( )里面增加了曝光时间结束的判断
   2. IPbus FIFO block read, 添加了空读次数限制，超过次数则退出。默认值为100。
    ```python   
    def read_ipb_data_fifo(self, reg_name_base, fifo_name, num, safe_mode, try_time=100): 
    ```
- [ ] run.py里面实现上述循环和判断步骤（测试人员应该逐步学会修改run.py来实现自己的想法）
   1. 新增了SCurve类，实现Pulse_Low 递增测试要求。
   2. 请在run.py的main_config中设置是否启动s-curve，以及main()中设置相关参数。

**Comment by Yunpeng-Lu** [comment]
Debug分支测试：
1、读出Sector0的数据正确，第一部分修改没问题。
2、自动扫描Sector0的S-curve（条件与周一手动扫描相同）：
      >read_ipb_data_fifo(1, safe_mode = True)，此处应该设为slice_size（与GS模式相同），因为有多个像素同时测试；
      >修改为50后，输出数据符合预期；
      >后续进一步比较自动扫描和手动扫描得出的结果有何不同

**Comment by habrade** [comment]
> Debug分支测试：
> 2、自动扫描Sector0的S-curve（条件与周一手动扫描相同）：
> >read_ipb_data_fifo(1, safe_mode = True)，此处应该设为slice_size（与GS模式相同），因为有多个像素同时测试；
> >修改为50后，输出数据符合预期；

This has been fixed, see debug bfcda17
